/**
 * This class is generated by jOOQ
 */
package org.jooq.example.db.oracle;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Justin extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1433983333;

	/**
	 * The singleton instance of <code>JUSTIN</code>
	 */
	public static final Justin JUSTIN = new Justin();

	/**
	 * No further instances allowed
	 */
	private Justin() {
		super("JUSTIN");
	}
}
